### ISSUE TITLE
Questions about your "Linear Layer Parameter Update Derivations"

### ISSUE THREAD

**Issue by PixelChen24** [YuanJianhao508/RAG-Driver#1]
Hi, your work is really inspiring. But I'm a little confused about the `Linear Layer Parameter Update Derivations` part of your paper.

In your paper in the section `Appendix` - `D.Linear Layer Parameter Update Derivations`, you say:
![image](https://github.com/YuanJianhao508/RAG-Driver/assets/36230079/bbbdad0e-3eb8-48ef-8dce-88b3df98cf04)
What does this mean? In the formula $(W+\Delta W)x$, $\Delta W$ is the derivative of $W$, but $\Delta W_{ICL}$ seems not to be the derivative of $W_{ZSL}$. So do you make this assumption just because this formula looks like that format?

Look forward to your further explanation, thank you very much.

**Comment by YuanJianhao508** [comment]
Hey @PixelChen24, sorry for the late reply (just saw the issue with the closed message. Yes the dual form of linear attention with ICL samples resembles the ΔW in standard GD, which is computed with the gradient of weight. This allows us to implicitly update the model parameter during inference time and without access to gradient!

**Comment by PixelChen24** [comment]
> Hey @PixelChen24, sorry for the late reply (just saw the issue with the closed message. Yes the dual form of linear attention with ICL samples resembles the ΔW in standard GD, which is computed with the gradient of weight. This allows us to implicitly update the model parameter during inference time and without access to gradient!

I see, thank you very much for your explanation!
