### ISSUE TITLE
why using test data for retrieval

### ISSUE THREAD

**Issue by javyduck** [YuanJianhao508/RAG-Driver#12]
Hi authors, thanks for your work!

I have a question regarding the use of test data during retrieval.

Could you kindly clarify why test data is also included for retrieval? I thought test data should primarily be reserved for evaluation. Shouldn't we be retrieving only from training videos?

https://github.com/YuanJianhao508/RAG-Driver/blob/24a0bd01f56c6fa4f2563a4c94925856e2ba707e/retrieval/BDDX_RAG_tuned_vpmatch_t13.json#L8

Thanks for your time and assistance!

**Comment by YuanJianhao508** [comment]
Hi @javyduck  thanks for raising the question! When training the retriever, we combined both the training and test datasets to train the projector. However, during the retrieval and training VLM, we do not we the test data. Thank you very much!
