### ISSUE TITLE
Question of  "database of driver experience"

### ISSUE THREAD

**Issue by lucien-ye** [YuanJianhao508/RAG-Driver#3]
![image](https://github.com/YuanJianhao508/RAG-Driver/assets/6427096/98b02f83-bfa2-420f-a497-afa53707b71d)
![image](https://github.com/YuanJianhao508/RAG-Driver/assets/6427096/f8ad74f8-dd52-4828-b24d-e7feb0f20ab8)

Your work is very interesting. But I have  a little confused about the  "retrieval database of driver experience" remaking on the picture above.  The database seems constructed by the history of the generation results?
Look forward to your further explanation, thank you very much.

**Comment by YuanJianhao508** [comment]
Hi @lucien-ye ,
Thank you for your question! The "retrieval database of driver experience" is consist with human expert demonstration (i.e. driving video + human annotation of driving action explanation and justification). In principle, the model generated explanation can also be updated to the database, but we haven't examinate this in our project.
