### ISSUE TITLE
When will the processed version of BDDX be available?

### ISSUE THREAD

**Issue by Xiaolong-RRL** [YuanJianhao508/RAG-Driver#4]
Dear author:

thanks for your great work!

I wander when will the processed version of BDDX and the full training progress be available?

**Comment by YuanJianhao508** [comment]
Hi @Xiaolong-RRL , 

Thank you for your interest in our work!
We have just uploaded the processed BDD-X in the repo. For training code, currently it can be done with minimal one sample training, the retrieval engine is still under cleaning. We will try to update that asap!

Best regards,
Jianhao

**Comment by Xiaolong-RRL** [comment]
Thanks for your quickly reply~

but it seems that there is some problem about the video_process.zip you have uploaded, and it cannot be decompressed normally.

**Comment by UltramanSleepless** [comment]
Hello! I ocur the problem. It seems that you have forget the file "final" in your video_process.zip
FileNotFoundError: [Errno 2] No such file or directory: 'video_process/final/conversation_bddx_train.json'

**Comment by YuanJianhao508** [comment]
Hi @Xiaolong-RRL ,

I have just update the link to the processed BDDX dataset, maybe you can have another try?

Best Regards,
Jianhao

**Comment by Xiaolong-RRL** [comment]
> Hi @Xiaolong-RRL ,
> 
> I have just update the link to the processed BDDX dataset, maybe you can have another try?
> 
> Best Regards, Jianhao

The current version file can be used normally. Thank you for your prompt reply～
