### ISSUE TITLE
how to generate the conversation_bddx_train.json in the finetuning script

### ISSUE THREAD

**Issue by uobinxiao** [YuanJianhao508/RAG-Driver#5]
Hello, thank you very much for sharing the dataset and code. I am trying to reproduce the results in your paper. I found the finetuning script is using conversation_bddx_train.json and conversation_bddx_eva.json. How should I generate these two files from the processed BDDX dataset?

**Comment by YuanJianhao508** [comment]
Hi @uobinxiao , 
Thank you for your question! You can first download the BDD-X data provided in the google drive link, and then specify the path to the data in video_process/create_bddx_json.py, and then run the script. However, it currently only support base conversation template. The ICL will be availabe in next release!
