### ISSUE TITLE
about evaluation

### ISSUE THREAD

**Issue by chenghuang66** [YuanJianhao508/RAG-Driver#6]
I don't see the part of RAG-ICL during reasoning, is this part of the code not yet available.

**Comment by YuanJianhao508** [comment]
Hi @chenghuang66 , thank you for your question! The evaluation part of is in llava.serve.eval_custom_chunck; the retrieval engine part is yet not available. We will let you know when it is available in the next release

**Comment by chenghuang66** [comment]
Thank you for your reply. Looking forward to further updates to the code.
