### ISSUE TITLE
when will the retrieval engine codebase release?

### ISSUE THREAD

**Issue by Xiaolong-RRL** [YuanJianhao508/RAG-Driver#8]
Dear author~

From the experiments in the paper, I see that after adding RA-ICL, the model achieves amazing high performance, which makes me look forward to implementing this part. 

So I would like to ask when the RA-ICL codebase will be released? I am looking forward to it~

Best Regards,
Xiaolong

**Comment by YuanJianhao508** [comment]
Hi @Xiaolong-RRL , thank you for your interesting in our work! We are currently progressively cleaning and updating this repo, we will update you once we upload your requested part!
